### ISSUE TITLE
Shutdown button

### ISSUE THREAD

**Issue by jason0597** [d0k3/SafeSigHaxInstaller#27]
When the sighaxed firm installation finishes, can there also be another button besides <A> for shutting down the console (so that you don't have to press and hold the power button for ~7 seconds to shut down the 3DS)?

**Comment by d0k3** [comment]
Why would you want that instead of the reboot? I'd have to assume after installing b9s, you already put teh CFW files on the SD, so you can just restart?

**Comment by jason0597** [comment]
Since B9S-NTR boots from `boot.firm` instead of something else (like `ntrboot.firm`), when you do the ntrboot button combination to boot into safeb9sinstaller, you install the sighaxed firm, and then you press A and then you are in an infinite loop of safeb9sinstaller. You can't really have two conflicting `boot.firm`s (luma's and safeb9sinstaller's), and you have to press and hold the power button to shut down the 3DS and change out the `boot.firm`.

**Comment by urherenow** [comment]
nothing to do with SafeB9SInstaller. It's boot9strap that needs the _ntr version (the one that gets flashed to the DS cart) to look for ntrboot.firm. Then you simply name SafeB9SInstaller ntrboot.firm and have luma as boot.firm at the same time. I do this myself but end up building boot9strap twice since that part is hard-coded. Not sure if it can be done in one go using a variable  (that gets changed in the Makefile between building Boot9Strap_ntr.firm and Boot9Strap.firm) or not...

**Comment by d0k3** [comment]
@urherenow is right - a ntrboot card shouldn't be set up to boot the same file a fully set up system would boot.

I'm recommending this b9s fork for ntrboot installs:
https://github.com/al3x10m/boot9strap/releases
... the only change here being `boot.firm` -> `ntrboot.firm`

You've got other options, too. Use GodMode9 to install the `boot9strap.firm` (can't mess up, you've got ntrboot, right?), or just pull out the SD card when you get the success message, set up from PC, reinsert, reboot.

The fix you mentioned here really does not warrant a new release, so I'm closing this now.
