### ISSUE TITLE
sighaxed firm not recognized

### ISSUE THREAD

**Issue by pandaalaska** [d0k3/SafeSigHaxInstaller#29]
so i'm installing boot9strap on a stock new 3ds with secret_sector.bin in the boot9strap folder on my sd, where the guide says to put. but i still fail the check for sighaxed firm

**Comment by urherenow** [comment]
Please post on gbatemp. This isn't a support forum. If you're working with a stock console, why are you trying (and failing) to read the a9lh to b9s part of the guide? Read the entire guide first to get an idea of what's going on. Then read it again while performing the steps.

"Note that, only on New 3DS, secret_sector.bin is needed to revert the arm9loaderhax exploit, which is why it is not needed for the installation of boot9strap on a stock console."

Do you even have boot9strap.firm.sha and boot9strap.firm in that folder?

**Comment by d0k3** [comment]
What @urherenow said - this isn't for support, but strictly for bug reports and feature requests.
